### ISSUE TITLE
Придумать сюжет

### ISSUE THREAD

**Issue by Smert** [stasizon/space-clicker#1]
Разработать сюжет и продумать сеттинг игры. Типа мы в космосе и убиваем корабли и монстров, которые встречаются у нас на пути. Нанимаем наёмников на свою сторону за разную цену, прокачиваем их. Как тебе такая идея?

**Comment by stasizon** [comment]
Неплохо, но это же обычной кликер

**Comment by Smert** [comment]
Я слушаю твои предложения

**Comment by stasizon** [comment]
Нажимаешь на кнопку - запускается ракета - даются деньги. Нанимаешь инженеров и некоторое количество денег будет приходить само без участия игрока.

**Comment by Smert** [comment]
И что тебе даст запуск ракеты?

**Comment by stasizon** [comment]
Ну я ж говорю запустил ракету - получил деньги

**Comment by Smert** [comment]
Так быстро игра надоест. Нужно постоянно занимать чем-то игрока. А так он либо по одной ракете в день будет пускать либо игру за день пройдёт

**Comment by Smert** [comment]
А с них нужно ещё бабла поиметь

**Comment by stasizon** [comment]
По иметь бабла с игры на которой я гит осваивают? Хорошие планы )

**Comment by Smert** [comment]
Кстати. Как тебе хостинг? Вроде лучше, чем народ

**Comment by stasizon** [comment]
А тут есть лимиты?

**Comment by Smert** [comment]
1GB

**Comment by stasizon** [comment]
Ясно, ладно все завтра
